# Generated by Django 4.1.2 on 2022-10-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_class_students_remove_class_teachers_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='classes',
            field=models.ManyToManyField(related_name='students', to='classes.class'),
        ),
    ]
