# Generated by Django 4.1.2 on 2022-10-19 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_options_class_date_created'),
        ('students', '0002_studentprofile_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentship', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentship', to='students.studentprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='classes',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='classes',
            field=models.ManyToManyField(related_name='students', through='students.ClassStudent', to='classes.class'),
        ),
    ]
