# Generated by Django 4.1.2 on 2022-11-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_options_class_date_created'),
        ('students', '0003_classstudent_alter_studentprofile_classes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classstudent',
            unique_together={('student', 'class_name')},
        ),
    ]
