# Generated by Django 4.1.2 on 2022-10-19 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_classteacher_teacherprofile_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
