# Generated by Django 4.1.2 on 2022-11-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_options_class_date_created'),
        ('teachers', '0003_classteacher_date_added'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together={('teacher', 'class_name')},
        ),
    ]
