# Generated by Django 4.1.2 on 2022-12-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_rename_class_course_alter_course_options'),
        ('teachers', '0004_alter_classteacher_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassTeacher',
            new_name='CourseTeacher',
        ),
        migrations.RenameField(
            model_name='courseteacher',
            old_name='class_name',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='courseteacher',
            unique_together={('teacher', 'course')},
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='classes',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', through='teachers.CourseTeacher', to='classes.course'),
        ),
    ]
