# Generated by Django 4.1.2 on 2023-02-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_rename_classteacher_courseteacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
