# Generated by Django 4.1.2 on 2022-10-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_remark_date_solution_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='date_marked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
