# Generated by Django 4.1.2 on 2022-11-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_date_announcement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, max_length=20000, null=True, upload_to='files/'),
        ),
    ]
