# Generated by Django 4.1.2 on 2022-10-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('STUDENT', 'student'), ('STAFF', 'staff')], default='ADMIN', max_length=50),
        ),
    ]
